name: Test CI

on: [push, pull_request]

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Build binary
        run: shards build

      - name: Run tests
        run: crystal spec
